apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - image: registry.ci.openshift.org/openshift:cluster-api-provider-vsphere
        name: manager
